name: Lab 4 (Lint and Unit Test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Deps
        run: npm install

      - name: Run Lint
        run: npm run lint

  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Deps
        run: npm install

      - name: Run Unit Tests
        run: npm run test:ci

      - if: success() || failure() 
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-${{ github.sha }}
          path: coverage/lcov-report